### PR TITLE
removed scapy dependency

### PR DESCRIPTION
**Pull request by gnany07**
Instead of importing whole scapy,
imported only necessay modules

### CODE REVIEW

**Comment by rcvaram** [comment]
It is good @gnany07  but I have to remove scapy dependency from the repo

**Comment by gnany07** [comment]
okay,you meant to have  independent ARP, Ether.. modules from somewhere else?
I didn't get the exact intention.

**Comment by rcvaram** [comment]
I have planned to remove imports of scapy from the repo. Simply, we can copy those relevant files only and get the required things from that file. Do you think, it can be done or not

**Comment by gnany07** [comment]
Yeah sure. It can be done.
Let me give it a try and then update you.

**Comment by gnany07** [comment]
Hi ram, I tried decouple the scapy package from the project.
I could get the each modules source code but the hard part here is all these are implemented with lot of inter-dependency with other modules and have some decorators

**Comment by rcvaram** [comment]
Not good as a straight forward answer from me, Don't worry I will look at it and update it later

**Pull request closed without merging**
