### PR TITLE
Feature/show os name

### PR DESCRIPTION
**Pull request by ahmadsyafrudin**
we can use scapy nmap_fp to "guess" operating system by ip address that we scan. we can use pretty table to make dynamic table size. please review this Pull Request.  This Pull Request is for issue number #1 

example

Thank you.

### CODE REVIEW

**Comment by rcvaram** [comment]
I will not have a plan to include any dependencies other than scapy. I have to get the OS version from the basic not from the nmap. I knew that was easier however This application will not be depend on the nmap

**Comment by erdepe-dad** [comment]
Ok. I'll try to rework untill met with your requirement.

**Comment by rcvaram** [comment]
Yeah sure,

**Comment by erdepe-dad** [comment]
all


I already remove dependencies other than scapy.  This is explanation where we get Operating System Information like showed on the picture above. 

Windows and Linux/Unix operating systems have different TTL starting values that are used by default. This factor can be used to attempt to fingerprint the type of operating system with which you are communicating. These values are summarized in the following table:

Operating system | Standard TTL value
-- | --
Microsoft Windows OS | 128
Linux/Unix OS | 64

@cvaram96 kindly review this Pull request. Thank you
issue #1

**Review by rcvaram — COMMENTED** [review]
Awesome work, I will review before today night bro

**Comment by erdepe-dad** [comment]
Yeah sure. Thank you

**Comment by rcvaram** [comment]
Can you tell your medium user name, I can tag you there, Good work

**Comment by erdepe-dad** [comment]
no problem,happy to help. @cvaram96  [my medium](https://medium.com/@sulekwer) .

**Pull request merged**
